summary: Update Search Trends Settings
operationId: search_trends#update_settings
tags:
- Search Trends
security:
- basicAuth: []
description: You must be Admin+.
requestBody:
  content:
    application/x-www-form-urlencoded:
      schema:
        type: object
        properties:
          search_trend_settings[trends_enabled]:
            type: boolean
          search_trend_settings[trends_displayed]:
            type: boolean
          search_trend_settings[trends_min_today]:
            type: integer
          search_trend_settings[trends_min_delta]:
            type: integer
          search_trend_settings[trends_min_ratio]:
            type: number
            format: float
          search_trend_settings[trends_ip_limit]:
            type: integer
          search_trend_settings[trends_ip_window]:
            type: integer
          search_trend_settings[trends_tag_limit]:
            type: integer
          search_trend_settings[trends_tag_window]:
            type: integer
responses:
  200:
    "$ref": "../../components/responses/messageSuccess.yaml"
  403:
    "$ref": "../../components/responses/accessDenied.yaml"
