name: Deploy Github Pages
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts
      - name: Build
        run: pnpm run build:production
      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist

  # Deploy job
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
